name: rbase
version: 0.1.0
homepage: https://github.com/morloclib/rcore
synopsis: Morloc prelude and serialization engine for R
description: Morloc prelude and serialization engine for R. Still evolving in
  tandem with the C++ and Python3 cousins. See
  https://github.com/morloc-project/morloc for more info on the morloc language
  itself.
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloclib/rcore
bug-reports: https://github.com/morloclib/rcore/issues
