name: rcore
version: 0.0.0
homepage: https://github.com/morloc-project/
synopsis: Core types and functions for R
description: Lots of detail about all this
category: language-base
license: MIT
author: "Zebulun Arendsee"
maintainer: "zbwrnz@gmail.com"
github: https://github.com/morloc-project/rcore
bug-reports: https://github.com/morloc-project/rcore
